### ISSUE TITLE
Templatize monitor query threshold values

### ISSUE THREAD

**Issue by dosullivan** [reactiveops/rodd#1]
Currently, the thresholds used in the `query` and `threshold` fields of the default monitor templates such as [cluster_bytes_received](https://github.com/reactiveops/rodd/blob/master/pentagon_datadog/monitors/kubernetes/cluster_bytes_received.yml) and [cluster_iops](https://github.com/reactiveops/rodd/blob/master/pentagon_datadog/monitors/kubernetes/cluster_iops.yml) are arbitrary values. It would be great if we could templatize these values, so that they could be easily overridden in the RODD yaml when they aren't appropriate. In those scenarios where deviations are necessary, one would only need to provide a value for the threshold instead of overriding the entire query.  

Additionally, if we had templated threshold values, perhaps we could provide arrays of values that are appropriate for a variety of common AWS instance sizes and then call upon those as appropriate.

**Comment by mjhuber** [comment]
this request was implemented in #46 - closing.
