### ISSUE TITLE
monitor kube-state-metrics are being exported into dd

### ISSUE THREAD

**Issue by crmejia** [reactiveops/rodd#35]
A few monitors depend specifically on kube-state-metrics  that is being deployed by the datadog chart. However, if these metrics are missing the monitors simply got to a _no data state_ and we are not alerted.

**Comment by mjhuber** [comment]
this could affect any monitor, not just monitors that rely on kube-state-metrics.  We could set the `notify_no_data` and `no_data_timeframe` variables on the monitor definitions, which would send an event when no data is received.

**Comment by crmejia** [comment]
I was not aware of these variables. I think they would work perfectly.
